name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Setup multilingual files
        run: node scripts/build-multilingual.js

      - name: Copy prerendered pages for SEO (without overwriting SPA entry)
        run: |
          # Ensure dist exists
          mkdir -p dist
          # Copy everything from public-pages except the root index.html and /en/index.html
          rsync -av public-pages/ dist/ --exclude '/index.html' --exclude '/en/index.html'
          echo "✓ Copied prerendered pages (kept dist/index.html and dist/en/index.html)"
          # Remove any dev-only script tags that reference source files
          if command -v grep >/dev/null; then
            MATCHED_FILES=$(grep -rl "src/main.tsx" dist || true)
            if [ -n "$MATCHED_FILES" ]; then
              echo "$MATCHED_FILES" | xargs sed -i '\|src/main\.tsx|d'
              echo "✓ Removed dev script tags from prerendered pages"
            fi
          fi

      - name: Inject SPA assets into prerendered pages
        run: node scripts/inject-spa-assets.cjs

      - name: Create .nojekyll file
        run: touch dist/.nojekyll

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
